### ISSUE TITLE
Where to get Utils?

### ISSUE THREAD

**Issue by rerb** [toburger/elm-drag-drop-sorting#1]
Can't find the Utils package imported.  Where should I look?

```
> import Main
I cannot find module 'Utils'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

>
```

**Comment by toburger** [comment]
My bad! Somehow I forgot to commit the `Utils.elm` file.
I don't have the original Utils.elm anymore, but I think my reverse engineered file should do the job: https://github.com/toburger/elm-drag-drop-sorting/blob/master/Utils.elm.
